### ISSUE TITLE
MSC non-lichenized fungi

### ISSUE THREAD

**Issue by themerekat** [iDigBio/gbif-comparison#1]
GBIF dataset: https://www.gbif.org/dataset/8fe64528-38fe-47c8-938a-b2ab603a653a
Endpoint: https://www.mycoportal.org/portal/content/dwca/MSC_DwC-A.zip

**Comment by CatChapman** [comment]
in the ingestion queue

**Comment by CatChapman** [comment]
ingested https://www.idigbio.org/portal/recordsets/0266a3f4-872b-4d21-a6b4-5c9818d8742b
