### ISSUE TITLE
VPI Fungi

### ISSUE THREAD

**Issue by ljwalker** [iDigBio/gbif-comparison#2]
GBIF dataset: https://www.gbif.org/dataset/d1f09ff9-d38d-4bd9-b8b2-bde0768c495c
Endpoint: https://www.mycoportal.org/portal/content/dwca/VPI_DwC-A.zip

**Comment by CatChapman** [comment]
same deal as UCSC, we ingest from a likely outdated MyCoPortal endpoint, not sure if manual fixing is necessary, but have pinged Dan so we can ensure data are up to date.

**Comment by CatChapman** [comment]
endpoint updated; closing
