### ISSUE TITLE
USFS-GILA herbarium

### ISSUE THREAD

**Issue by ljwalker** [iDigBio/gbif-comparison#21]
Already in iDigBio (could be refreshed): https://www.idigbio.org/portal/recordsets/c13a5966-99a3-4383-b9ef-259cf46800fe

Now also in GBIF: https://www.gbif.org/dataset/4e07968c-842b-4c22-8f57-ac14a9e7934b

**Comment by CatChapman** [comment]
thanks! looks like it has since been refreshed.
