### ISSUE TITLE
UT-M fungarium

### ISSUE THREAD

**Issue by ljwalker** [iDigBio/gbif-comparison#24]
This collection is now publishing to GBIF: https://www.mycoportal.org/portal/collections/misc/collprofiles.php?collid=85

https://www.idigbio.org/portal/recordsets/33b015c8-455c-438a-89dc-c936bf3af0e1

https://www.gbif.org/dataset/fa8041ba-449c-4dde-8a51-b18892a8c806

**Comment by CatChapman** [comment]
thank you!
