### ISSUE TITLE
USMS lichens & bryophytes

### ISSUE THREAD

**Issue by ljwalker** [iDigBio/gbif-comparison#25]
The USMS herbarium is now also publishing its lichen and bryophyte data to GBIF: 

https://www.idigbio.org/portal/recordsets/c3134980-bf5c-49b8-a289-790d45f02c86

https://www.gbif.org/dataset/search?publishing_org=9e32fce1-f6fe-4825-a185-4e05cc41bad2

Lichens: https://lichenportal.org/portal/collections/misc/collprofiles.php?collid=173
Bryos: https://bryophyteportal.org/portal/collections/misc/collprofiles.php?collid=132

**Comment by CatChapman** [comment]
thank you! adding lichens and bryo to iDB queue as we don't have those specific datasets (small as they may be, they are still valuable :) )
