### ISSUE TITLE
UCSC Fungi

### ISSUE THREAD

**Issue by ljwalker** [iDigBio/gbif-comparison#3]
GBIF dataset: https://www.gbif.org/dataset/e7c31c32-27e2-43d8-9d64-5d76a264664b
Endpoint: https://www.mycoportal.org/portal/content/dwca/UCSC_DwC-A.zip

**Comment by CatChapman** [comment]
we are ingesting these data already, albeit from a different endpoint (still from MyCoPortal, though) https://www.idigbio.org/portal/recordsets/2c00d087-1df6-4744-807d-056be36eed0d

I've pinged Dan in case we need to manually switch where we are ingesting from.

**Comment by CatChapman** [comment]
endpoint has been switched
