### ISSUE TITLE
NEB (x3): Fungi, Bryophyes, Lichen

### ISSUE THREAD

**Issue by ljwalker** [iDigBio/gbif-comparison#4]
**Fungi**
- GBIF dataset: https://www.gbif.org/dataset/f662a646-1c95-47c4-bd92-ef1fa8834725
- Endpoint: https://www.mycoportal.org/portal/content/dwca/NEB_DwC-A.zip

**Bryophytes**
- GBIF dataset: https://www.gbif.org/dataset/869551f8-1c58-45fd-9c50-3a2aff12ad55
- Endpoint: https://bryophyteportal.org/portal/content/dwca/NEB_DwC-A.zip

**Lichens**
- GBIF dataset: https://www.gbif.org/dataset/95f402d7-d151-4cce-b0ec-2b78d771b6f3
- Endpoint: https://lichenportal.org/cnalh/content/dwca/NEB_DwC-A.zip

**Comment by CatChapman** [comment]
already being ingested; see https://www.idigbio.org/portal/recordsets/bbf5f8ed-f33f-40ba-9d0d-1c24dfec4193 https://www.idigbio.org/portal/recordsets/ced8c9bc-e8b5-49e7-860a-289fc913860c and https://www.idigbio.org/portal/recordsets/8f3b62fb-56ec-49e8-9f8f-bb257348291f
