### ISSUE TITLE
GAM Fungi

### ISSUE THREAD

**Issue by ljwalker** [iDigBio/gbif-comparison#5]
GBIF dataset: https://www.gbif.org/dataset/b0a8bd29-e038-43c7-82cc-383141123890
Endpoint: https://www.mycoportal.org/portal/content/dwca/GAM_DwC-A.zip

**Comment by CatChapman** [comment]
added to ingestion queue

**Comment by CatChapman** [comment]
ingested (as of a month ago; whoops) https://www.idigbio.org/portal/recordsets/9cecfba6-6501-401c-9043-e95ba70164f3
