### ISSUE TITLE
TAC vascular plants

### ISSUE THREAD

**Issue by ljwalker** [iDigBio/gbif-comparison#8]
Refresh requested: https://www.idigbio.org/portal/recordsets/c7ae0ade-c23e-4fe6-a3d4-79bd973374c2

GBIF dataset: https://www.gbif.org/dataset/049b3ca8-8533-4606-8acf-7b2e2c7a74f5

**Comment by CatChapman** [comment]
refresh for what purpose - data refresh? or metadata? or both?

in any case, all data gets automatically refreshed anytime we ingest and reindex, save for recordsets who have changed DwC-A endpoints, etc. it doesn't seem like any URLs have changed for this recordset so I unless I am mistaken, having these data refreshed is a "sit and wait" situation.

**Comment by ljwalker** [comment]
Refresh for both data and metadata. TAC has added more records since March 2022, albeit only a few.

**Comment by CatChapman** [comment]
Last Ingested Date: 2023-01-11

closing
