### ISSUE TITLE
TLU vascular plants

### ISSUE THREAD

**Issue by ljwalker** [iDigBio/gbif-comparison#9]
https://www.gbif.org/dataset/28cde3da-b84d-484b-8273-f2ab6e9352d1

https://www.idigbio.org/portal/recordsets/1fc07b28-43f5-49d1-badf-63005e1c3e9a

**Comment by CatChapman** [comment]
Since we are already ingesting these data - what action do we want taken? A data update? The last ingested date is December 06 2022, and there's less than a 100-record difference between the iDB and GBIF record counts, so I think no action is needed here? Correct me if I'm wrong. :)

**Comment by ljwalker** [comment]
No action seems reasonable since there's been an ingestion since the issue was opened.
